services:
  database:
    image: postgres:16-alpine
    container_name: santeclaire_db
    environment:
      POSTGRES_DB: santeclaire
      POSTGRES_USER: app
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: santeclaire_pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@santeclaire.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database

  backend:
    build:
      context: ./backend
    container_name: santeclaire_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "postgresql://app:root@database:5432/santeclaire?serverVersion=16&charset=utf8"
    depends_on:
      - database

  chatbot:
    build:
      context: ./chatbot-SanteClaire
    container_name: santeclaire_chatbot
    ports:
      - "3001:3001"
    env_file:
      - ./chatbot-SanteClaire/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: santeclaire_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:8000/api"
      VITE_CHATBOT_URL: "http://localhost:3001/api"
    depends_on:
      - backend
      - chatbot

volumes:
  db_data: