import { createContext, useContext, useState, useEffect } from 'react'

const STORAGE_KEY = 'santeclaire_lang'
const SUPPORTED_LANGS = ['fr', 'en']
const DEFAULT_LANG = 'fr'
const LanguageContext = createContext()

/**
 * Détecte la langue préférée du navigateur.
 * Utilisée uniquement au premier chargement si aucune préférence n'est stockée.
 */
function getBrowserLanguage() {
  try {
    if (typeof navigator === 'undefined') return DEFAULT_LANG
    const lang = (navigator.language || navigator.userLanguage || '').toLowerCase()
    const code = lang.split(/[-_]/)[0] || ''
    if (code === 'fr') return 'fr'
    if (code === 'en') return 'en'
  } catch (_) {}
  return 'en'
}

/**
 * Retourne la langue à utiliser : préférence stockée > langue navigateur > défaut.
 */
function getInitialLanguage() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (stored && SUPPORTED_LANGS.includes(stored)) return stored
  } catch (_) {}
  try {
    return getBrowserLanguage()
  } catch (_) {
    return DEFAULT_LANG
  }
}

export const translations = {
  fr: {
    // Navigation & Header
    'nav.home': 'Accueil',
    'nav.features': 'Fonctionnalités',
    'nav.security': 'Sécurité',
    'nav.how': 'Comment ça marche',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',

    // Hero
    'hero.badge': 'Plateforme certifiée HDS — Conforme RGPD',
    'hero.title_part1': 'Vos documents',
    'hero.title_part2': 'médicaux,',
    'hero.title_part3': 'enfin simples.',
    'hero.description': 'SantéClaire connecte patients et médecins autour d\'un dossier médical unique, partagé en toute confiance, accessible en un clic lors de vos consultations.',
    'hero.cta': 'Créer mon compte gratuit',
    'hero.demo': 'Voir comment ça marche',
    'hero.stats1': '12k+',
    'hero.stats1_label': 'Patients actifs',
    'hero.stats2': '850+',
    'hero.stats2_label': 'Médecins certifiés',
    'hero.stats3': '99.9%',
    'hero.stats3_label': 'Disponibilité',

    // Features
    'features.title': 'Nos Fonctionnalités',
    'features.subtitle_visual': 'Tout ce dont vous\navez besoin.',
    'features.subtitle': 'Des outils pensés pour simplifier le parcours de soin, côté patient comme côté médecin.',
    'features.ai': 'Assistant IA médical',
    'features.ai_desc': "Posez vos questions sur vos ordonnances, résultats d'analyses ou posologie. L'IA analyse vos documents pour des réponses précises et personnalisées.",
    'features.transcription': 'Transcription automatique',
    'features.transcription_desc': "Le médecin enregistre la consultation, Whisper transcrit en temps réel et l'IA génère un compte rendu structuré et signable en un clic.",
    'features.family': 'Gestion de la famille',
    'features.family_desc': "Gérez les dossiers médicaux de vos proches en tant que représentant légal. Tutelle, représentation parentale — tout est pris en charge.",
    'features.access': 'Accès temporaire RGPD',
    'features.access_desc': "Votre médecin accède à vos documents uniquement pendant la durée de la consultation. L'accès expire automatiquement — vous gardez le contrôle.",

    // Security
    'security.label': 'Sécurité',
    'security.title': 'Votre santé mérite la meilleure protection.',
    'security.subtitle': 'SantéClaire respecte les standards les plus stricts de sécurité des données de santé. Vos informations n\'appartiennent qu\'\u00e0 vous.',
    'security.description': 'Toutes les données sont hébergées exclusivement en France sur des infrastructures certifiées HDS (Hébergeur de Données de Santé). L\'accès \u00e0 vos documents est tracé, auditable et révocable \u00e0 tout moment.',
    'security.hds': 'Hébergement certifié HDS',
    'security.hds_sub': 'Données hébergées en France',
    'security.encryption': 'Chiffrement de bout en bout',
    'security.gdpr': 'Conforme RGPD',
    'security.gdpr_sub': 'Droit \u00e0 l\'oubli & portabilité',
    'security.prosante': 'ProSanté Connect',
    'security.prosante_sub': 'Authentification médecins certifiée',

    // How it works
    'how.label': 'Comment ça marche',
    'how.title': 'Simple pour tout le monde.',
    'how.subtitle': 'En 3 étapes, gérez l\'intégralité de votre parcours de santé depuis une seule plateforme.',
    'how.step1_title': 'Centralisez',
    'how.step1_desc': 'Uploadez tous vos documents médicaux — ordonnances, résultats d\'analyses, comptes rendus — en un seul endroit sécurisé et accessible partout.',
    'how.step2_title': 'Contrôlez',
    'how.step2_desc': 'Choisissez précisément ce que vous partagez avec chaque médecin. Vos documents sont partagés par défaut, mais vous gardez le contrôle total à tout moment.',
    'how.step3_title': 'Consultez',
    'how.step3_desc': 'Donnez un accès temporaire à votre médecin pendant la durée exacte du rendez-vous. L\'accès expire automatiquement — conformément au RGPD.',

    // For Who
    'forwho.label': 'Pour qui ?',
    'forwho.title': 'Une plateforme, deux espaces.',
    'forwho.subtitle': 'Que vous soyez patient ou professionnel de santé, SantéClaire s\'adapte à vos besoins.',
    'forwho.patient_title': 'Espace Patient',
    'forwho.patient_desc': 'Reprenez le contrôle de votre santé. Centralisez, organisez et partagez vos documents médicaux en toute sérénité.',
    'forwho.patient_feature1': 'Centralisation de tous vos documents',
    'forwho.patient_feature2': 'Assistant IA disponible 24h/7j',
    'forwho.patient_feature3': 'Partage sécurisé avec votre médecin',
    'forwho.patient_feature4': 'Gestion des dossiers familiaux',
    'forwho.patient_feature5': 'Notifications et rappels RDV',
    'forwho.patient_cta': 'Créer mon espace patient',
    'forwho.doctor_title': 'Espace Médecin',
    'forwho.doctor_desc': 'Gagnez du temps à chaque consultation. Résumé IA, transcription automatique, comptes rendus générés en un clic.',
    'forwho.doctor_feature1': 'Résumé IA des antécédents patient',
    'forwho.doctor_feature2': 'Transcription vocale → compte rendu',
    'forwho.doctor_feature3': 'Accès sécurisé aux documents partagés',
    'forwho.doctor_feature4': 'Signature électronique intégrée',
    'forwho.doctor_feature5': 'Conforme aux exigences HDS',
    'forwho.doctor_cta': 'Créer mon espace médecin',

    // Page titles
    'title.default': 'SantéClaire — Votre dossier médical, enfin simple',

    // Footer
    'footer.product': 'Produit',
    'footer.company': 'Entreprise',
    'footer.legal': 'Légal',
    'footer.features': 'Fonctionnalités',
    'footer.security': 'Sécurité',
    'footer.pricing': 'Tarifs',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    'footer.privacy': 'Confidentialité',
    'footer.desc': 'La plateforme qui connecte patients et médecins autour d\'un dossier médical sécurisé et partagé.',
    'footer.rights': 'Tous droits réservés',
    'footer.hds': 'HDS Certifié',
    'footer.encrypted': 'Chiffré',
    'footer.patientSpace': 'Espace Patient',
    'footer.doctorSpace': 'Espace Médecin',
    'footer.blog': 'Blog',
    'footer.press': 'Presse',
    'footer.careers': 'Carrières',
    'footer.terms': 'CGU',
    'footer.legalNotice': 'Mentions légales',
    'footer.gdpr': 'RGPD',

    // Nav
    'nav.about': 'À propos',

    // Auth / Login
    'auth.register': 'Créer un compte',
    'auth.login': 'Se connecter',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.name': 'Nom complet',
    'auth.phone': 'Téléphone',
    'auth.submit': 'Continuer',
    'auth.back': 'Retour',
    'auth.login_title': 'Connexion',
    'auth.login_subtitle': 'Accédez à votre espace personnel',
    'auth.welcome_title': 'Bienvenue sur SantéClaire',
    'auth.welcome_subtitle': 'La plateforme qui connecte patients et médecins en toute sécurité.',
    'auth.patient': 'Patient',
    'auth.doctor': 'Médecin',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.sign_in': 'Se connecter',
    'auth.no_account': 'Pas encore de compte ?',
    'auth.create_account': 'Créer un compte',
    'auth.secure_login': 'Connexion sécurisée • Données hébergées en France',
    'auth.email_placeholder': 'votre@email.fr',

    // Register
    'register.who_are_you': 'Qui êtes-vous ?',
    'register.select_profile': 'Sélectionnez votre profil pour créer votre compte.',
    'register.back_home': "Retour à l'accueil",
    'register.i_am_patient': 'Je suis patient',
    'register.i_am_doctor': 'Je suis médecin',
    'register.patient_desc': 'Centralisez vos documents médicaux, partagez-les avec vos médecins et consultez votre Assistant IA pour mieux comprendre vos soins.',
    'register.doctor_desc': 'Accédez aux dossiers de vos patients, utilisez la transcription IA et générez vos comptes rendus automatiquement en quelques clics.',
    'register.patient_feature1': 'Inscription en 2 minutes',
    'register.patient_feature2': 'Aucun document requis',
    'register.patient_feature3': 'Gratuit',
    'register.doctor_feature1': 'Vérification sous 24-48h',
    'register.doctor_feature2': 'Documents professionnels requis',
    'register.doctor_feature3': 'Accès complet après validation',
    'register.validation_required': 'Validation requise',
    'register.continue_patient': 'Continuer en tant que patient',
    'register.continue_doctor': 'Continuer en tant que médecin',
    'register.have_account': 'Vous avez déjà un compte ?',
    'register.footer': '© 2024 SantéClaire — Plateforme de santé sécurisée',
    'register.legal': 'Mentions légales',
    'register.privacy': 'Confidentialité',
    'register.help': 'Aide',
    
    // Patient pages - Sidebar
    'sidebar.dashboard': 'Tableau de bord',
    'sidebar.documents': 'Documents',
    'sidebar.appointments': 'Rendez-vous',
    'sidebar.family': 'Profils Famille',
    'sidebar.messages': 'Messages',
    'sidebar.ai': 'Assistant IA',
    'sidebar.settings': 'Paramètres',
    'sidebar.profile': 'Mon Profil',
    'sidebar.logout': 'Déconnexion',
    'sidebar.rights': 'Gestion des droits',
    'sidebar.chatbot': 'Chatbot',

    // Doctor pages - Sidebar
    'doctor.dashboard': 'Tableau de bord',
    'doctor.patients': 'Mes Patients',
    'doctor.schedule': 'Planning',
    'doctor.documents': 'Documents',
    'doctor.records': 'Dossiers Médicaux',
    'doctor.messages': 'Messages',
    'doctor.consultations': 'Consultations',
    'doctor.statistics': 'Statistiques',
    'doctor.settings': 'Paramètres',
    'doctor.logout': 'Déconnexion',
    'doctor.addPatientBtn': 'Ajouter un patient',
    'doctor.addPatientPageTitle': 'Ajouter un patient',
    'doctor.addPatientPageDesc': 'Saisissez les informations du patient. Une invitation à rejoindre SantéClaire peut être envoyée par e-mail.',
    'doctor.addPatientBack': 'Retour',
    'doctor.addPatientFirstName': 'Prénom',
    'doctor.addPatientLastName': 'Nom',
    'doctor.addPatientEmail': 'E-mail',
    'doctor.addPatientPhone': 'Téléphone',
    'doctor.addPatientBirthDate': 'Date de naissance',
    'doctor.addPatientGender': 'Sexe',
    'doctor.addPatientGenderPlaceholder': 'Sélectionner…',
    'doctor.addPatientGenderFemale': 'Femme',
    'doctor.addPatientGenderMale': 'Homme',
    'doctor.addPatientGenderOther': 'Autre / non précisé',
    'doctor.addPatientNir': 'Numéro de sécurité sociale',
    'doctor.addPatientNotes': 'Notes médicales ou administratives',
    'doctor.addPatientOptional': 'facultatif',
    'doctor.addPatientInviteEmail': 'Envoyer une invitation à créer un compte SantéClaire à cette adresse e-mail',
    'doctor.addPatientRequiredHint': 'Les champs marqués * sont obligatoires.',
    'doctor.addPatientSubmit': 'Enregistrer le patient',
    'doctor.addPatientCancel': 'Annuler',
    'doctor.addPatientSuccess': 'Patient enregistré (démonstration)',
    'doctor.addPatientSuccessHint': 'Les données ont été validées localement. En production, le patient recevra une invitation si l’option est cochée.',
    'doctor.addPatientBackToList': 'Retour à la liste des patients',

    // Common
    'common.profile': 'Mon Profil',
    'common.name': 'Jean Dupont',
    'common.patientId': 'ID Patient: JD_2023',
    'common.familyProfiles': 'Profils Famille',
    'common.manageFamilyRights': 'Gérer les droits d\'accès',
    'common.accessToDashboard': 'Accéder à mon tableau de bord',
    'common.arrow': '→',

    // Patient Dashboard
    'dashboard.searchPlaceholder': 'Rechercher un document, un médecin...',
    'dashboard.activeFile': 'DOSSIER ACTIF :',
    'dashboard.add': 'Ajouter',
    'dashboard.ageMe': '— Moi',
    'dashboard.ageYears': '— {age} ans',
    'dashboard.hello': 'Bonjour, {name}',
    'dashboard.welcomeBack': 'Heureux de vous revoir. Voici un aperçu de votre santé aujourd\'hui.',
    'dashboard.atAGlance': 'En un coup d\'œil',
    'dashboard.new': 'NOUVEAU',
    'dashboard.myNextAppointment': 'PREMIER MON PROCHAIN RDV',
    'dashboard.downloaded2DaysAgo': 'Téléchargée il y a 2 jours',
    'dashboard.view': 'Consulter ›',
    'dashboard.drChen': 'Dr. Chen - Cardiologue',
    'dashboard.friday1030': 'Vendredi à 10:30',
    'dashboard.documentsSelected': '3 DOCUMENTS SÉLECTIONNÉS',
    'dashboard.manageSharing': 'Gérer le partage ›',
    'dashboard.shared': 'PARTAGÉ',
    'dashboard.makePrivate': 'X Rendre privé',
    'dashboard.sharingDefault': 'Vos documents sont partagés par défaut avec votre médecin lors d\'un rendez-vous.',
    'dashboard.managePreferences': 'Gérer vos préférences ›',
    'dashboard.addDocument': 'Ajouter un document',
    'dashboard.dragDrop': 'Glissez-déposez ici',
    'dashboard.uploadFormats': 'PDF, JPG ou PNG (Max 10Mb)',
    'dashboard.browseFiles': 'Parcourir mes fichiers',
    'dashboard.aiAssistant': 'Assistant IA',
    'dashboard.available247': 'DISPONIBLE 24/7',
    'dashboard.aiDesc': 'Posez vos questions sur vos résultats d\'analyses ou vos prochains rendez-vous.',
    'dashboard.startDiscussion': 'Lancer une discussion',
    'dashboard.familyProfiles': 'Profils Famille',
    'dashboard.profilesCount': '3 profils associés à votre compte SantéClaire.',
    'dashboard.supportHealth': 'SUPPORT SANTÉ',
    'dashboard.needHelp': 'Besoin d\'aide avec vos documents ?',
    'dashboard.contactAdvisor': 'Contacter un conseiller',
    'dashboard.prescriptionDrMartin': 'Ordonnance Dr. Martin',
    'dashboard.bloodResults': 'Résultats Analyses de Sang',
    'dashboard.prescriptionMeds': 'Ordonnance Médicaments',
    'dashboard.labBioSante': 'Laboratoire BioSanté Paris',
    'dashboard.drDurand': 'Dr. Durand - Médecin Généraliste',
    'dashboard.dateOct24': '24 OCTOBRE 2023',
    'dashboard.dateSep12': '12 SEPTEMBRE 2023',

    // Patient Documents
    'documents.searchPlaceholder': 'Rechercher un document, une analyse...',
    'documents.myDocuments': 'Mes Documents',
    'documents.manageDesc': 'Gérez et partagez vos documents médicaux en toute sécurité.',
    'documents.all': 'Tous',
    'documents.prescriptions': 'Ordonnances',
    'documents.analyses': 'Analyses',
    'documents.imaging': 'Imagerie',
    'documents.reports': 'Comptes-rendus',
    'documents.forAppointment': 'Pour mon RDV',
    'documents.dropTitle': 'Déposez vos documents ici',
    'documents.dropDesc': 'PDF, JPEG ou PNG (Max. 10 Mo par fichier). Vos documents sont chiffrés de bout en bout.',
    'documents.uploadAdded': '{count} document(s) ajouté(s) à votre liste (démonstration).',
    'documents.visibleBy': 'Documents visibles par Dr. Smith — RDV 24 Oct 2023',
    'documents.modifySelection': 'Modifier la sélection',
    'documents.sharedDefaultInfo': 'Vos documents sont partagés par défaut avec votre médecin lors d\'un rendez-vous.',
    'documents.learnMore': 'En savoir plus sur le RGPD →',
    'documents.accessExpires': 'Accès expire dans 34:12',
    'documents.document': 'DOCUMENT',
    'documents.category': 'CATÉGORIE',
    'documents.dateAdded': 'DATE D\'AJOUT',
    'documents.status': 'STATUT',
    'documents.actions': 'ACTIONS',
    'documents.shared': 'Partagé',
    'documents.private': 'Privé',
    'documents.download': 'Télécharger',
    'documents.delete': 'Supprimer',
    'documents.confirmDelete': 'Supprimer ce document ?',
    'documents.menuMore': 'Plus d’actions',
    'documents.menuMakePrivate': 'Rendre privé',
    'documents.menuMakePublic': 'Rendre public (partager avec le médecin)',
    'documents.storageUsed': 'Stockage utilisé',
    'documents.secureStorage': 'Stockage sécurisé HDS',

    // Patient Family Profiles
    'family.searchPlaceholder': 'Rechercher un membre...',
    'family.title': 'Gestion de la famille',
    'family.subtitle': 'Gérez les accès et consultez les dossiers médicaux de vos proches en toute sécurité.',
    'family.addMember': 'Ajouter un membre',
    'family.hintText': 'Pour consulter ou gérer le dossier d\'un proche, utilisez le sélecteur de profil en haut de votre tableau de bord.',
    'family.goToDashboard': 'Aller au tableau de bord →',
    'family.members': 'Membres de la famille',
    'family.member': 'MEMBRE',
    'family.relation': 'RELATION / ÂGE',
    'family.type': 'TYPE',
    'family.lastUpdate': 'DERNIÈRE MISE À JOUR',
    'family.accessLevel': 'NIVEAU D\'ACCÈS',
    'family.actions': 'ACTIONS',
    'family.me': 'Moi',
    'family.daughter': 'Fille',
    'family.father': 'Père',
    'family.legalRep': 'Représentant légal',
    'family.legalGuardian': 'Tutelle légale',
    'family.familyAssistant': 'Assistance familiale',
    'family.fullAccess': 'Accès complet',
    'family.readOnly': 'Lecture seule',
    'family.archived': 'Archivé',
    'family.ago2Days': 'Il y a 2 jours',
    'family.ago5Days': 'Il y a 5 jours',
    'family.profileSnapshot': 'Aperçu rapide des profils',
    'family.update2j': 'MISE À JOUR : 2J',
    'family.connected': 'CONNECTÉ',
    'family.legalRepFull': 'REPRÉSENTANT LÉGAL — ACCÈS COMPLET',
    'family.familyAidReadOnly': 'AIDANT FAMILIAL — LECTURE SEULE',
    'family.pediatrics': 'Suivi pédiatrique & Vaccinations',
    'family.geriatrics': 'Gériatrie & Cardiologie',
    'family.viewDashboard': 'Voir le tableau de bord',
    'family.manageDoctorRights': 'Gérer les droits d\'accès médicins',
    'family.rgpdNote': 'Conformément au RGPD, l\'accès aux données de santé de vos proches est strictement encadré.',
    'family.encryptionNote': 'SantéClaire utilise un chiffrement de bout-en-bout pour garantir la confidentialité des dossiers médicaux.',
    'family.termsOfUse': 'Conditions d\'utilisation',
    'family.assistance': 'Assistance',
    'family.years': 'ans',

    // Patient Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez votre compte et vos préférences de sécurité.',
    'settings.searchPlaceholder': 'Rechercher...',
    'settings.myProfile': 'MON PROFIL',
    'settings.photoFormat': 'Format JPG ou PNG, max 5MB',
    'settings.firstName': 'Prénom',
    'settings.lastName': 'Nom',
    'settings.phone': 'Téléphone',
    'settings.saveChanges': 'Enregistrer les modifications',
    'settings.security': 'SÉCURITÉ & CONNEXION',
    'settings.changePassword': 'Changer le mot de passe',
    'settings.currentPassword': 'Mot de passe actuel',
    'settings.newPassword': 'Nouveau mot de passe',
    'settings.confirmPassword': 'Confirmer le mot de passe',
    'settings.show': 'Afficher',
    'settings.hide': 'Masquer',
    'settings.updatePassword': 'Mettre à jour le mot de passe',
    'settings.twoFactor': 'Authentification à deux facteurs (2FA)',
    'settings.twoFactorDesc': 'Sécurisez davantage votre compte en utilisant une application d\'authentification sur par SMS.',
    'settings.activeSessions': 'Sessions actives',
    'settings.connectedNow': 'Connecté à l\'instant',
    'settings.currentSession': 'Session actuelle',
    'settings.revoke': 'Révoquer',
    'settings.revokeAll': 'Déconnecter tous les appareils',
    'settings.privacy': 'CONFIDENTIALITÉ & RGPD',
    'settings.shareByDefault': 'Partager mes documents par défaut',
    'settings.shareByDefaultDesc': 'Autoriser les praticiens à consulter mes antécédents médicaux lors d\'un rendez-vous.',
    'settings.dataPortability': 'Droit à la portabilité',
    'settings.dataPortabilityDesc': 'Télécharger une copie intégrale de vos données de santé stockées sur nos serveurs.',
    'settings.exportData': 'Exporter mes données (JSON/PDF)',
    'settings.rightToForget': 'Droit à l\'oubli',
    'settings.rightToForgetDesc': 'Cette action est irréversible. Toutes vos données médicales seront supprimées définitivement.',
    'settings.deleteAccount': 'Supprimer mon compte et mes données',
    'settings.notifications': 'PRÉFÉRENCES DE NOTIFICATION',
    'settings.notifType': 'TYPE DE NOTIFICATION',
    'settings.appointmentReminders': 'Rappels de rendez-vous',
    'settings.appointmentRemindersDesc': '24h avant votre visite',
    'settings.newDocuments': 'Nouveaux documents médicaux',
    'settings.newDocumentsDesc': 'Résultats d\'analyses, comptes-rendus',
    'settings.securityAlerts': 'Alertes de sécurité',
    'settings.securityAlertsDesc': 'Connexion suspecte, changement de MDP',
    'settings.footer': '© 2024 SantéClaire - Hébergement de Données de Santé (HDS) certifié. Conformité RGPD assurée.',

    // Patient Confirm
    'confirm.step1': 'ÉTAPE 1/2 : VOS',
    'confirm.step1Title': 'INFORMATIONS',
    'confirm.step2': 'ÉTAPE 2/2 :',
    'confirm.step2Title': 'CONFIRMATION',
    'confirm.congrats': 'Félicitations, votre compte',
    'confirm.isCreated': 'est créé !',
    'confirm.welcome': 'Bienvenue sur SantéClaire, votre espace santé sécurisé.',
    'confirm.checkEmail': 'Vérifiez votre boîte mail',
    'confirm.checkEmailDesc': 'Un lien de confirmation vous a été envoyé pour valider votre accès.',
    'confirm.completeDossier': 'Complétez votre dossier',
    'confirm.completeDossierDesc': 'Commencez à uploader vos premiers documents pour centraliser votre santé.',
    'confirm.talkToAI': 'Parlez à l\'Assistant IA',
    'confirm.talkToAIDesc': 'Posez vos questions pour préparer au mieux votre premier RDV médical.',
    'confirm.needHelp': 'Besoin d\'aide ?',
    'confirm.contactSupport': 'Contactez notre support',

    // Patient Manage Rights
    'rights.familyMembers': 'Membres de la famille',
    'rights.manageRights': 'Gérer les droits',
    'rights.secureAccess': 'ACCÈS SÉCURISÉ',
    'rights.globalAccess': 'Niveau d\'accès global',
    'rights.fullAccess': 'Accès complet',
    'rights.fullAccessDesc': 'Peut consulter, télécharger et gérer tous les dossiers et rendez-vous médicaux.',
    'rights.viewOnly': 'Lecture seule',
    'rights.viewOnlyDesc': 'Peut consulter l\'historique et les documents mais ne peut pas modifier ou supprimer.',
    'rights.noAccess': 'Aucun accès',
    'rights.noAccessDesc': 'Révoque tout accès aux données personnelles et historiques médicaux.',
    'rights.granularPermissions': 'Permissions granulaires',
    'rights.medicalReports': 'Comptes rendus médicaux',
    'rights.medicalReportsDesc': 'Résumés, détails chirurgie, comptes rendus d\'hospitalisation.',
    'rights.prescriptions': 'Ordonnances',
    'rights.prescriptionsDesc': 'Listes de médicaments actifs et passés, renouvellements pharmacie.',
    'rights.labResults': 'Résultats de laboratoire',
    'rights.labResultsDesc': 'Analyses sanguines, imagerie (IRM, scanner), rapports d\'anatomopathologie.',
    'rights.upcomingAppointments': 'Rendez-vous à venir',
    'rights.upcomingAppointmentsDesc': 'Dates, lieux et détails des médecins pour les visites futures.',
    'rights.revokeAccess': 'Révoquer l\'accès maintenant',
    'rights.docSharing': 'Partage individuel de documents',
    'rights.allSharedByDefault': 'Tous les documents sont partagés par défaut. Décochez ceux que vous souhaitez garder privés.',
    'rights.docName': 'NOM DU DOCUMENT',
    'rights.date': 'DATE',
    'rights.category': 'CATÉGORIE',
    'rights.shared': 'PARTAGÉ',
    'rights.viewAllDocs': 'Voir tous les 12 documents',
    'rights.changesEffective': 'Les modifications prennent effet immédiatement sur tous les appareils.',
    'rights.cancel': 'Annuler',
    'rights.saveChanges': 'Enregistrer les modifications',
    'rights.memberSince': 'Membre depuis 2021',
    'rights.lastActivity': 'Dernière activité : il y a 2 heures',

    // Chatbot / AI
    'chatbot.searchPlaceholder': 'Poser une question sur votre santé, vos médicaments...',
    'chatbot.title': 'Consultation avec SantéClaire AI',
    'chatbot.activeAnalysis': 'ANALYSE EN COURS',
    'chatbot.frequentTopics': 'SUJETS FRÉQUENTS',
    'chatbot.howCanIHelp': 'Comment puis-je vous aider ?',
    'chatbot.prepareAppointment': 'Préparer mon RDV',
    'chatbot.understandPrescription': 'Comprendre mon ordonnance',
    'chatbot.understandResults': 'Comprendre mes résultats',
    'chatbot.generalQuestion': 'Question générale',
    'chatbot.restartWithRdv': 'Relancer avec RDV',
    'chatbot.myPrescriptions': 'Mes ordonnances',
    'chatbot.myResults': 'Mes résultats',
    'chatbot.needUrgentHelp': 'Besoin d\'aide urgente ?',
    'chatbot.urgentHelpDesc': 'Appelez votre clinique ou les urgences immédiatement.',
    'chatbot.contactClinic': 'CONTACTER LA CLINIQUE',
    'chatbot.encrypted': 'Chiffré de bout en bout',
    'chatbot.hipaa': 'Conforme HIPAA',
    'chatbot.attachFile': 'Joindre un fichier',
    'chatbot.scanDocument': 'Importer un document',
    'chatbot.uploadContext': 'Fichiers joints',
    'chatbot.voiceInput': 'Entrée vocale',
    'chatbot.voiceNotSupported': 'La reconnaissance vocale n’est pas disponible sur ce navigateur.',

    // Doctor Dashboard
    'doctor.searchPlaceholder': 'Rechercher patients, fichiers ou dossiers...',
    'doctor.today': 'DATE DU JOUR',
    'doctor.consultationsToday': 'Consultations aujourd\'hui',
    'doctor.pendingReports': 'Rapports en attente',
    'doctor.sharedDocuments': 'Documents partagés',
    'doctor.urgentLabResults': 'Résultats urgents',
    'doctor.signRequired': 'Signature requise',
    'doctor.last24h': 'Dernières 24h',
    'doctor.critical': 'Critique',
    'doctor.todayPlanning': 'Planning du jour',
    'doctor.viewCalendar': 'Voir le calendrier',
    'doctor.arrived': 'Arrivé(e)',
    'doctor.waiting': 'En attente',
    'doctor.ongoing': 'En cours',
    'doctor.planned': 'Planifié(e)',
    'doctor.viewProfile': 'Voir le profil',
    'doctor.startConsultation': 'Démarrer une consultation',
    'doctor.onDuty': 'EN SERVICE',
    'doctor.criticalAlerts': 'Alertes critiques',
    'doctor.actionRequired': 'ACTION REQUISE',
    'doctor.criticalResult': 'Résultat critique',
    'doctor.reportPending': 'Rapport en attente',
    'doctor.contactPatient': 'CONTACTER LE PATIENT →',
    'doctor.signNow': 'SIGNER MAINTENANT →',
    'doctor.sharedFiles': 'Fichiers partagés',
    'doctor.viewAllDocuments': 'Voir tous les documents',
    'doctor.reports': 'Rapports',
    'doctor.cardiology': 'Cardiologie',
    'doctor.expiresIn': 'Expire dans 28:45',
    'doctor.apptRoutine': 'Bilan de routine • Suivi diabète',
    'doctor.apptTeleconsult': 'Téléconsultation • Renouvellement ordonnance',
    'doctor.apptUrgent': 'Consultation urgente • Douleur thoracique aiguë',
    'doctor.apptAnnual': 'Bilan annuel • Révision analyses',
    'doctor.reportPendingDesc': 'Le compte rendu de Sarah Connor nécessite votre signature.',
    'doctor.practitionerSpace': 'ESPACE PRATICIEN',
    'doctor.professionalProfileTitle': 'Mon Profil Professionnel',
    'doctor.professionalProfileSubtitle': 'Gérez vos informations et votre visibilité sur la plateforme',
    'doctor.navMyProfile': 'Mon Profil',
    'doctor.verified': 'Vérifié',
    'doctor.generalPractice': 'Médecine Générale',
    'doctor.rppsStatusLine': 'RPPS: 1010123456 • Statut: Praticien certifié',
    'doctor.certifiedPractitioner': 'Praticien certifié',
    'doctor.modifyPhoto': 'Modifier la photo',
    'doctor.professionalInfo': 'Informations Professionnelles',
    'doctor.lastName': 'Nom',
    'doctor.firstName': 'Prénom',
    'doctor.dateOfBirth': 'Date de naissance',
    'doctor.specialty': 'Spécialité',
    'doctor.languagesSpoken': 'Langues parlées',
    'doctor.practiceLocation': 'Lieu d\'exercice',
    'doctor.structure': 'Structure',
    'doctor.address': 'Adresse',
    'doctor.cityZip': 'Ville / CP',
    'doctor.phonePro': 'Tél. Pro',
    'doctor.emailPro': 'Email Pro',
    'doctor.idNumbers': 'Numéros d\'Identification',
    'doctor.toolsSoftware': 'Outils & Logiciels',
    'doctor.managementSoftware': 'Logiciel de gestion',
    'doctor.digitalSignature': 'Signature numérique',
    'doctor.active': 'Active',
    'doctor.saveProfile': 'Sauvegarder les modifications',
    'doctor.hdsBadge': 'DONNÉES CERTIFIÉES HDS',
    'profile.dossierUpToDate': 'DOSSIER À JOUR',
  },
  en: {
    // Navigation & Header
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.security': 'Security',
    'nav.how': 'How it works',
    'nav.login': 'Login',
    'nav.signup': 'Sign up',

    // Hero
    'hero.badge': 'HDS-Certified Platform — GDPR Compliant',
    'hero.title_part1': 'Your medical',
    'hero.title_part2': 'documents,',
    'hero.title_part3': 'finally simple.',
    'hero.description': 'SantéClaire connects patients and doctors around a unique medical file, shared with confidence, accessible with just one click during your consultations.',
    'hero.cta': 'Create my free account',
    'hero.demo': 'See how it works',
    'hero.stats1': '12k+',
    'hero.stats1_label': 'Active Patients',
    'hero.stats2': '850+',
    'hero.stats2_label': 'Certified Doctors',
    'hero.stats3': '99.9%',
    'hero.stats3_label': 'Availability',

    // Features
    'features.title': 'Our Features',
    'features.subtitle_visual': 'Everything you\nneed.',
    'features.subtitle': 'Tools designed to simplify the care journey, for both patients and doctors.',
    'features.ai': 'Medical AI Assistant',
    'features.ai_desc': "Ask questions about your prescriptions, test results or dosage. The AI analyzes your documents for accurate and personalized answers.",
    'features.transcription': 'Automatic Transcription',
    'features.transcription_desc': "The doctor records the consultation, Whisper transcribes it in real time and the AI generates a structured and signable report in one click.",
    'features.family': 'Family Management',
    'features.family_desc': "Manage your loved ones' medical files as a legal representative. Guardianship, parental representation — everything is handled.",
    'features.access': 'Temporary GDPR Access',
    'features.access_desc': "Your doctor only accesses your documents during the consultation. Access expires automatically — you stay in control.",

    // Security
    'security.label': 'Security',
    'security.title': 'Your health deserves the best protection.',
    'security.subtitle': 'SantéClaire respects the strictest standards for health data security. Your information belongs only to you.',
    'security.description': 'All data is hosted exclusively in France on HDS-certified (Health Data Hosting) infrastructures. Access to your documents is traced, auditable and revocable at any time.',
    'security.hds': 'HDS Certified Hosting',
    'security.hds_sub': 'Data hosted in France',
    'security.encryption': 'End-to-end encryption',
    'security.gdpr': 'GDPR Compliant',
    'security.gdpr_sub': 'Right to be forgotten & portability',
    'security.prosante': 'ProSanté Connect',
    'security.prosante_sub': 'Certified doctor authentication',

    // How it works
    'how.label': 'How it works',
    'how.title': 'Simple for everyone.',
    'how.subtitle': 'In 3 steps, manage your entire health journey from one platform.',
    'how.step1_title': 'Centralize',
    'how.step1_desc': 'Upload all your medical documents — prescriptions, test results, medical reports — in one secure place accessible everywhere.',
    'how.step2_title': 'Control',
    'how.step2_desc': 'Choose exactly what you share with each doctor. Your documents are private by default, but you maintain full control at all times.',
    'how.step3_title': 'Consult',
    'how.step3_desc': 'Give your doctor temporary access during the exact appointment duration. Access expires automatically — GDPR compliant.',

    // For Who
    'forwho.label': 'For Whom?',
    'forwho.title': 'One platform, two spaces.',
    'forwho.subtitle': 'Whether you\'re a patient or healthcare professional, SantéClaire adapts to your needs.',
    'forwho.patient_title': 'Patient Space',
    'forwho.patient_desc': 'Take control of your health. Centralize, organize, and securely share your medical documents.',
    'forwho.patient_feature1': 'Centralization of all your documents',
    'forwho.patient_feature2': 'AI assistant available 24/7',
    'forwho.patient_feature3': 'Secure sharing with your doctor',
    'forwho.patient_feature4': 'Family file management',
    'forwho.patient_feature5': 'Notifications and appointment reminders',
    'forwho.patient_cta': 'Create my patient space',
    'forwho.doctor_title': 'Doctor Space',
    'forwho.doctor_desc': 'Save time on every consultation. AI summary, automatic transcription, reports generated in one click.',
    'forwho.doctor_feature1': 'AI summary of patient history',
    'forwho.doctor_feature2': 'Voice transcription → medical report',
    'forwho.doctor_feature3': 'Secure access to shared documents',
    'forwho.doctor_feature4': 'Integrated electronic signature',
    'forwho.doctor_feature5': 'HDS compliant',
    'forwho.doctor_cta': 'Create my doctor space',

    // Page titles
    'title.default': 'SantéClaire — Your medical file, finally simple',

    // Footer
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.features': 'Features',
    'footer.security': 'Security',
    'footer.pricing': 'Pricing',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy',
    'footer.desc': 'The platform that connects patients and doctors around a secure and shared medical file.',
    'footer.rights': 'All rights reserved',
    'footer.hds': 'HDS Certified',
    'footer.encrypted': 'Encrypted',
    'footer.patientSpace': 'Patient Space',
    'footer.doctorSpace': 'Doctor Space',
    'footer.blog': 'Blog',
    'footer.press': 'Press',
    'footer.careers': 'Careers',
    'footer.terms': 'Terms',
    'footer.legalNotice': 'Legal notice',
    'footer.gdpr': 'GDPR',

    // Nav
    'nav.about': 'About',

    // Auth / Login
    'auth.register': 'Create account',
    'auth.login': 'Sign in',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full name',
    'auth.phone': 'Phone',
    'auth.submit': 'Continue',
    'auth.back': 'Back',
    'auth.login_title': 'Sign in',
    'auth.login_subtitle': 'Access your personal space',
    'auth.welcome_title': 'Welcome to SantéClaire',
    'auth.welcome_subtitle': 'The platform that connects patients and doctors securely.',
    'auth.patient': 'Patient',
    'auth.doctor': 'Doctor',
    'auth.forgot_password': 'Forgot password?',
    'auth.sign_in': 'Sign in',
    'auth.no_account': "Don't have an account yet?",
    'auth.create_account': 'Create account',
    'auth.secure_login': 'Secure connection • Data hosted in France',
    'auth.email_placeholder': 'your@email.com',

    // Register
    'register.who_are_you': 'Who are you?',
    'register.select_profile': 'Select your profile to create your account.',
    'register.back_home': 'Back to home',
    'register.i_am_patient': 'I am a patient',
    'register.i_am_doctor': 'I am a doctor',
    'register.patient_desc': 'Centralize your medical documents, share them with your doctors and use your AI Assistant to better understand your care.',
    'register.doctor_desc': 'Access your patients\' files, use AI transcription and generate your medical reports automatically in a few clicks.',
    'register.patient_feature1': 'Registration in 2 minutes',
    'register.patient_feature2': 'No documents required',
    'register.patient_feature3': 'Free',
    'register.doctor_feature1': 'Verification within 24-48h',
    'register.doctor_feature2': 'Professional documents required',
    'register.doctor_feature3': 'Full access after validation',
    'register.validation_required': 'Validation required',
    'register.continue_patient': 'Continue as patient',
    'register.continue_doctor': 'Continue as doctor',
    'register.have_account': 'Already have an account?',
    'register.footer': '© 2024 SantéClaire — Secure health platform',
    'register.legal': 'Legal notice',
    'register.privacy': 'Privacy',
    'register.help': 'Help',
    
    // Patient pages - Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.documents': 'Documents',
    'sidebar.appointments': 'Appointments',
    'sidebar.family': 'Family Profiles',
    'sidebar.messages': 'Messages',
    'sidebar.ai': 'AI Assistant',
    'sidebar.settings': 'Settings',
    'sidebar.profile': 'My Profile',
    'sidebar.logout': 'Logout',
    'sidebar.rights': 'Manage Rights',
    'sidebar.chatbot': 'Chatbot',

    // Doctor pages - Sidebar
    'doctor.dashboard': 'Dashboard',
    'doctor.patients': 'My Patients',
    'doctor.schedule': 'Schedule',
    'doctor.documents': 'Documents',
    'doctor.records': 'Medical Records',
    'doctor.messages': 'Messages',
    'doctor.consultations': 'Consultations',
    'doctor.statistics': 'Statistics',
    'doctor.settings': 'Settings',
    'doctor.logout': 'Logout',
    'doctor.addPatientBtn': 'Add patient',
    'doctor.addPatientPageTitle': 'Add a patient',
    'doctor.addPatientPageDesc': 'Enter the patient’s details. An invitation to join SantéClaire can be sent by email.',
    'doctor.addPatientBack': 'Back',
    'doctor.addPatientFirstName': 'First name',
    'doctor.addPatientLastName': 'Last name',
    'doctor.addPatientEmail': 'Email',
    'doctor.addPatientPhone': 'Phone',
    'doctor.addPatientBirthDate': 'Date of birth',
    'doctor.addPatientGender': 'Gender',
    'doctor.addPatientGenderPlaceholder': 'Select…',
    'doctor.addPatientGenderFemale': 'Female',
    'doctor.addPatientGenderMale': 'Male',
    'doctor.addPatientGenderOther': 'Other / prefer not to say',
    'doctor.addPatientNir': 'National insurance number',
    'doctor.addPatientNotes': 'Medical or administrative notes',
    'doctor.addPatientOptional': 'optional',
    'doctor.addPatientInviteEmail': 'Send an invitation to create a SantéClaire account to this email address',
    'doctor.addPatientRequiredHint': 'Fields marked * are required.',
    'doctor.addPatientSubmit': 'Save patient',
    'doctor.addPatientCancel': 'Cancel',
    'doctor.addPatientSuccess': 'Patient saved (demo)',
    'doctor.addPatientSuccessHint': 'Data was validated locally. In production, the patient would receive an invitation if the option is enabled.',
    'doctor.addPatientBackToList': 'Back to patient list',

    // Common
    'common.profile': 'My Profile',
    'common.name': 'Jean Dupont',
    'common.patientId': 'Patient ID: JD_2023',
    'common.familyProfiles': 'Family Profiles',
    'common.manageFamilyRights': 'Manage Access Rights',
    'common.accessToDashboard': 'Access my dashboard',
    'common.arrow': '→',

    // Patient Dashboard
    'dashboard.searchPlaceholder': 'Search for a document, a doctor...',
    'dashboard.activeFile': 'ACTIVE FILE:',
    'dashboard.add': 'Add',
    'dashboard.ageMe': '— Me',
    'dashboard.ageYears': '— {age} yrs',
    'dashboard.hello': 'Hello, {name}',
    'dashboard.welcomeBack': 'Good to see you. Here\'s an overview of your health today.',
    'dashboard.atAGlance': 'At a glance',
    'dashboard.new': 'NEW',
    'dashboard.myNextAppointment': 'MY NEXT APPOINTMENT',
    'dashboard.downloaded2DaysAgo': 'Downloaded 2 days ago',
    'dashboard.view': 'View ›',
    'dashboard.drChen': 'Dr. Chen - Cardiologist',
    'dashboard.friday1030': 'Friday at 10:30',
    'dashboard.documentsSelected': '3 DOCUMENTS SELECTED',
    'dashboard.manageSharing': 'Manage sharing ›',
    'dashboard.shared': 'SHARED',
    'dashboard.makePrivate': 'X Make private',
    'dashboard.sharingDefault': 'Your documents are shared by default with your doctor during an appointment.',
    'dashboard.managePreferences': 'Manage preferences ›',
    'dashboard.addDocument': 'Add a document',
    'dashboard.dragDrop': 'Drag and drop here',
    'dashboard.uploadFormats': 'PDF, JPG or PNG (Max 10Mb)',
    'dashboard.browseFiles': 'Browse my files',
    'dashboard.aiAssistant': 'AI Assistant',
    'dashboard.available247': 'AVAILABLE 24/7',
    'dashboard.aiDesc': 'Ask questions about your test results or upcoming appointments.',
    'dashboard.startDiscussion': 'Start a discussion',
    'dashboard.familyProfiles': 'Family Profiles',
    'dashboard.profilesCount': '3 profiles linked to your SantéClaire account.',
    'dashboard.supportHealth': 'HEALTH SUPPORT',
    'dashboard.needHelp': 'Need help with your documents?',
    'dashboard.contactAdvisor': 'Contact an advisor',
    'dashboard.prescriptionDrMartin': 'Dr. Martin Prescription',
    'dashboard.bloodResults': 'Blood Test Results',
    'dashboard.prescriptionMeds': 'Prescription Medications',
    'dashboard.labBioSante': 'BioSanté Paris Lab',
    'dashboard.drDurand': 'Dr. Durand - General Practitioner',
    'dashboard.dateOct24': 'OCTOBER 24, 2023',
    'dashboard.dateSep12': 'SEPTEMBER 12, 2023',

    // Patient Documents
    'documents.searchPlaceholder': 'Search for a document, a test...',
    'documents.myDocuments': 'My Documents',
    'documents.manageDesc': 'Manage and share your medical documents securely.',
    'documents.all': 'All',
    'documents.prescriptions': 'Prescriptions',
    'documents.analyses': 'Lab Results',
    'documents.imaging': 'Imaging',
    'documents.reports': 'Reports',
    'documents.forAppointment': 'For my appointment',
    'documents.dropTitle': 'Drop your documents here',
    'documents.dropDesc': 'PDF, JPEG or PNG (Max 10MB per file). Your documents are end-to-end encrypted.',
    'documents.uploadAdded': '{count} document(s) added to your list (demo).',
    'documents.visibleBy': 'Documents visible by Dr. Smith — Appointment Oct 24, 2023',
    'documents.modifySelection': 'Modify selection',
    'documents.sharedDefaultInfo': 'Your documents are shared by default with your doctor during an appointment.',
    'documents.learnMore': 'Learn more about GDPR →',
    'documents.accessExpires': 'Access expires in 34:12',
    'documents.document': 'DOCUMENT',
    'documents.category': 'CATEGORY',
    'documents.dateAdded': 'DATE ADDED',
    'documents.status': 'STATUS',
    'documents.actions': 'ACTIONS',
    'documents.shared': 'Shared',
    'documents.private': 'Private',
    'documents.download': 'Download',
    'documents.delete': 'Delete',
    'documents.confirmDelete': 'Delete this document?',
    'documents.menuMore': 'More actions',
    'documents.menuMakePrivate': 'Make private',
    'documents.menuMakePublic': 'Make public (share with doctor)',
    'documents.storageUsed': 'Storage used',
    'documents.secureStorage': 'HDS secure storage',

    // Patient Family Profiles
    'family.searchPlaceholder': 'Search for a member...',
    'family.title': 'Family management',
    'family.subtitle': 'Manage access and view your loved ones\' medical records securely.',
    'family.addMember': 'Add a member',
    'family.hintText': 'To view or manage a loved one\'s file, use the profile selector at the top of your dashboard.',
    'family.goToDashboard': 'Go to dashboard →',
    'family.members': 'Family members',
    'family.member': 'MEMBER',
    'family.relation': 'RELATION / AGE',
    'family.type': 'TYPE',
    'family.lastUpdate': 'LAST UPDATE',
    'family.accessLevel': 'ACCESS LEVEL',
    'family.actions': 'ACTIONS',
    'family.me': 'Me',
    'family.daughter': 'Daughter',
    'family.father': 'Father',
    'family.legalRep': 'Legal representative',
    'family.legalGuardian': 'Legal guardian',
    'family.familyAssistant': 'Family assistant',
    'family.fullAccess': 'Full access',
    'family.readOnly': 'Read only',
    'family.archived': 'Archived',
    'family.ago2Days': '2 days ago',
    'family.ago5Days': '5 days ago',
    'family.profileSnapshot': 'Profile quick overview',
    'family.update2j': 'UPDATE: 2D',
    'family.connected': 'CONNECTED',
    'family.legalRepFull': 'LEGAL REPRESENTATIVE — FULL ACCESS',
    'family.familyAidReadOnly': 'FAMILY CAREGIVER — READ ONLY',
    'family.pediatrics': 'Pediatric follow-up & Vaccinations',
    'family.geriatrics': 'Geriatrics & Cardiology',
    'family.viewDashboard': 'View dashboard',
    'family.manageDoctorRights': 'Manage doctor access rights',
    'family.rgpdNote': 'In accordance with GDPR, access to your loved ones\' health data is strictly regulated.',
    'family.encryptionNote': 'SantéClaire uses end-to-end encryption to ensure medical record confidentiality.',
    'family.termsOfUse': 'Terms of use',
    'family.assistance': 'Assistance',
    'family.years': 'yrs',

    // Patient Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and security preferences.',
    'settings.searchPlaceholder': 'Search...',
    'settings.myProfile': 'MY PROFILE',
    'settings.photoFormat': 'JPG or PNG format, max 5MB',
    'settings.firstName': 'First name',
    'settings.lastName': 'Last name',
    'settings.phone': 'Phone',
    'settings.saveChanges': 'Save changes',
    'settings.security': 'SECURITY & LOGIN',
    'settings.changePassword': 'Change password',
    'settings.currentPassword': 'Current password',
    'settings.newPassword': 'New password',
    'settings.confirmPassword': 'Confirm password',
    'settings.show': 'Show',
    'settings.hide': 'Hide',
    'settings.updatePassword': 'Update password',
    'settings.twoFactor': 'Two-factor authentication (2FA)',
    'settings.twoFactorDesc': 'Secure your account further with an authentication app or SMS.',
    'settings.activeSessions': 'Active sessions',
    'settings.connectedNow': 'Connected just now',
    'settings.currentSession': 'Current session',
    'settings.revoke': 'Revoke',
    'settings.revokeAll': 'Sign out all devices',
    'settings.privacy': 'PRIVACY & GDPR',
    'settings.shareByDefault': 'Share my documents by default',
    'settings.shareByDefaultDesc': 'Allow practitioners to view my medical history during an appointment.',
    'settings.dataPortability': 'Right to data portability',
    'settings.dataPortabilityDesc': 'Download a full copy of your health data stored on our servers.',
    'settings.exportData': 'Export my data (JSON/PDF)',
    'settings.rightToForget': 'Right to be forgotten',
    'settings.rightToForgetDesc': 'This action is irreversible. All your medical data will be permanently deleted.',
    'settings.deleteAccount': 'Delete my account and data',
    'settings.notifications': 'NOTIFICATION PREFERENCES',
    'settings.notifType': 'NOTIFICATION TYPE',
    'settings.appointmentReminders': 'Appointment reminders',
    'settings.appointmentRemindersDesc': '24h before your visit',
    'settings.newDocuments': 'New medical documents',
    'settings.newDocumentsDesc': 'Lab results, reports',
    'settings.securityAlerts': 'Security alerts',
    'settings.securityAlertsDesc': 'Suspicious login, password change',
    'settings.footer': '© 2024 SantéClaire - HDS certified. GDPR compliance ensured.',

    // Patient Confirm
    'confirm.step1': 'STEP 1/2: YOUR',
    'confirm.step1Title': 'INFORMATION',
    'confirm.step2': 'STEP 2/2:',
    'confirm.step2Title': 'CONFIRMATION',
    'confirm.congrats': 'Congratulations, your account',
    'confirm.isCreated': 'has been created!',
    'confirm.welcome': 'Welcome to SantéClaire, your secure health space.',
    'confirm.checkEmail': 'Check your mailbox',
    'confirm.checkEmailDesc': 'A confirmation link has been sent to validate your access.',
    'confirm.completeDossier': 'Complete your file',
    'confirm.completeDossierDesc': 'Start uploading your first documents to centralize your health records.',
    'confirm.talkToAI': 'Talk to the AI Assistant',
    'confirm.talkToAIDesc': 'Ask questions to best prepare for your first medical appointment.',
    'confirm.needHelp': 'Need help?',
    'confirm.contactSupport': 'Contact our support',

    // Patient Manage Rights
    'rights.familyMembers': 'Family members',
    'rights.manageRights': 'Manage rights',
    'rights.secureAccess': 'SECURE ACCESS',
    'rights.globalAccess': 'Global access level',
    'rights.fullAccess': 'Full access',
    'rights.fullAccessDesc': 'Can view, download and manage all records and medical appointments.',
    'rights.viewOnly': 'View-only',
    'rights.viewOnlyDesc': 'Can view medical history and documents but cannot edit or delete.',
    'rights.noAccess': 'No access',
    'rights.noAccessDesc': 'Revokes all access to personal data and medical history.',
    'rights.granularPermissions': 'Granular permissions',
    'rights.medicalReports': 'Medical reports',
    'rights.medicalReportsDesc': 'Summary reports, surgery details, hospital discharge notes.',
    'rights.prescriptions': 'Prescriptions',
    'rights.prescriptionsDesc': 'Active and past medication lists, pharmacy renewals.',
    'rights.labResults': 'Lab results',
    'rights.labResultsDesc': 'Blood tests, imaging (MRI, CT), pathology reports.',
    'rights.upcomingAppointments': 'Upcoming appointments',
    'rights.upcomingAppointmentsDesc': 'Dates, locations and doctor details for future visits.',
    'rights.revokeAccess': 'Revoke access now',
    'rights.docSharing': 'Individual document sharing',
    'rights.allSharedByDefault': 'All documents are shared by default. Uncheck those you want to keep private.',
    'rights.docName': 'DOCUMENT NAME',
    'rights.date': 'DATE',
    'rights.category': 'CATEGORY',
    'rights.shared': 'SHARED',
    'rights.viewAllDocs': 'View all 12 documents',
    'rights.changesEffective': 'Changes take effect immediately on all devices.',
    'rights.cancel': 'Cancel',
    'rights.saveChanges': 'Save changes',
    'rights.memberSince': 'Member since 2021',
    'rights.lastActivity': 'Last activity: 2 hours ago',

    // Chatbot / AI
    'chatbot.searchPlaceholder': 'Ask about your health, meds...',
    'chatbot.title': 'Consultation with SantéClaire AI',
    'chatbot.activeAnalysis': 'ACTIVE ANALYSIS',
    'chatbot.frequentTopics': 'FREQUENT TOPICS',
    'chatbot.howCanIHelp': 'How can I help you?',
    'chatbot.prepareAppointment': 'Prepare my appointment',
    'chatbot.understandPrescription': 'Understand my prescription',
    'chatbot.understandResults': 'Understand my results',
    'chatbot.generalQuestion': 'General question',
    'chatbot.restartWithRdv': 'Restart with appointment',
    'chatbot.myPrescriptions': 'My prescriptions',
    'chatbot.myResults': 'My results',
    'chatbot.needUrgentHelp': 'Need urgent help?',
    'chatbot.urgentHelpDesc': 'Call your clinic or emergency services immediately.',
    'chatbot.contactClinic': 'CONTACT CLINIC',
    'chatbot.encrypted': 'End-to-end encrypted',
    'chatbot.hipaa': 'HIPAA Compliant',
    'chatbot.attachFile': 'Attach a file',
    'chatbot.scanDocument': 'Import a document',
    'chatbot.uploadContext': 'Attached files',
    'chatbot.voiceInput': 'Voice input',
    'chatbot.voiceNotSupported': 'Voice recognition is not supported in this browser.',

    // Doctor Dashboard
    'doctor.searchPlaceholder': 'Search patients, files, or records...',
    'doctor.today': 'TODAY\'S DATE',
    'doctor.consultationsToday': 'Consultations Today',
    'doctor.pendingReports': 'Pending Reports',
    'doctor.sharedDocuments': 'Shared Documents',
    'doctor.urgentLabResults': 'Urgent Lab Results',
    'doctor.signRequired': 'Sign required',
    'doctor.last24h': 'Last 24h',
    'doctor.critical': 'Critical',
    'doctor.todayPlanning': 'Today\'s schedule',
    'doctor.viewCalendar': 'View calendar',
    'doctor.arrived': 'Arrived',
    'doctor.waiting': 'Waiting',
    'doctor.ongoing': 'In progress',
    'doctor.planned': 'Scheduled',
    'doctor.viewProfile': 'View profile',
    'doctor.startConsultation': 'Start a consultation',
    'doctor.onDuty': 'ON DUTY',
    'doctor.criticalAlerts': 'Critical alerts',
    'doctor.actionRequired': 'ACTION REQUIRED',
    'doctor.criticalResult': 'Critical result',
    'doctor.reportPending': 'Report pending',
    'doctor.contactPatient': 'CONTACT PATIENT →',
    'doctor.signNow': 'SIGN NOW →',
    'doctor.sharedFiles': 'Shared files',
    'doctor.viewAllDocuments': 'View all documents',
    'doctor.reports': 'Reports',
    'doctor.cardiology': 'Cardiology',
    'doctor.expiresIn': 'Expires in 28:45',
    'doctor.apptRoutine': 'Routine check-up • Diabetes follow-up',
    'doctor.apptTeleconsult': 'Teleconsultation • Prescription renewal',
    'doctor.apptUrgent': 'Urgent consultation • Acute chest pain',
    'doctor.apptAnnual': 'Annual check-up • Test review',
    'doctor.reportPendingDesc': 'Sarah Connor\'s report requires your signature.',
    'doctor.practitionerSpace': 'PRACTITIONER SPACE',
    'doctor.professionalProfileTitle': 'My Professional Profile',
    'doctor.professionalProfileSubtitle': 'Manage your information and visibility on the platform',
    'doctor.navMyProfile': 'My Profile',
    'doctor.verified': 'Verified',
    'doctor.generalPractice': 'General Practice',
    'doctor.rppsStatusLine': 'RPPS: 1010123456 • Status: Certified practitioner',
    'doctor.certifiedPractitioner': 'Certified practitioner',
    'doctor.modifyPhoto': 'Change photo',
    'doctor.professionalInfo': 'Professional Information',
    'doctor.lastName': 'Last name',
    'doctor.firstName': 'First name',
    'doctor.dateOfBirth': 'Date of birth',
    'doctor.specialty': 'Specialty',
    'doctor.languagesSpoken': 'Languages spoken',
    'doctor.practiceLocation': 'Practice location',
    'doctor.structure': 'Practice',
    'doctor.address': 'Address',
    'doctor.cityZip': 'City / ZIP',
    'doctor.phonePro': 'Work phone',
    'doctor.emailPro': 'Work email',
    'doctor.idNumbers': 'Identification numbers',
    'doctor.toolsSoftware': 'Tools & Software',
    'doctor.managementSoftware': 'Practice management',
    'doctor.digitalSignature': 'Digital signature',
    'doctor.active': 'Active',
    'doctor.saveProfile': 'Save changes',
    'doctor.hdsBadge': 'HDS-CERTIFIED DATA',
    'profile.dossierUpToDate': 'FILE UP TO DATE',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => getInitialLanguage())

  const setLanguage = (lang) => {
    if (!SUPPORTED_LANGS.includes(lang)) return
    setLanguageState(lang)
    try {
      localStorage.setItem(STORAGE_KEY, lang)
    } catch (_) {}
  }

  useEffect(() => {
    try {
      document.documentElement.lang = language === 'en' ? 'en' : 'fr'
      document.title = translations[language]?.['title.default'] || 'SantéClaire'
    } catch (_) {}
  }, [language])

  /**
   * Traduction avec fallback propre :
   * 1. Clé dans la langue courante
   * 2. Clé dans l'autre langue (fr/en)
   * 3. Clé brute (évité au maximum)
   */
  const t = (key, vars = {}) => {
    const fallbackLang = language === 'en' ? 'fr' : 'en'
    let str = translations[language]?.[key]
      || translations[fallbackLang]?.[key]
      || key
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v ?? ''))
    })
    return str
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
